server.host: "0.0.0.0"
server.shutdownTimeout: "5s"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true
server.name: "boundary-demo-kibana"
server.publicBaseUrl: "http://localhost:5601"
